= Heimatpfleger Test PAge

In December 2013 Heimatpfleger of Leteln, link:http://www.sturma-online.de[J端rgen Sturma], wrote an important article about the history of the
Leteln school the Bleeke family's connection to it that revealed previously unknown facts about the Bleeke family's background.

== What is a Heimatfpleger?

Jurgen St端rma link:http://www.sturma-online.de[describes a Heimatpfleger] as:

====
Heritage custodians are mostly volunteers and officially appointed persons who are involved in heritage
preservation and similar areas in their area of responsibility. They advise and support districts and
independent towns, municipalities, museums, associations, schools, churches and private individuals.
They can be members of specialist committees of public administrations and often run a heritage association
themselves. The term "Heimatpfleger" was established by Otto Merkt.

A general distinction is made between full-time district heritage officers and honorary district heritage
officers, town or local heritage officers. The respective guidelines for local historians differ depending
on the federal state.
====

J端rgen Sturma's article, really two related articles, appeared in the December 2013 issue of the Leitler Blatt (Leitler Gazette)

 article reveal signifant, unknow details about the Bleeke family background.
The link:http://www.sturma-online.de/page0/styled/downloads-2/files/Leitler%20Blatt%202013-1.pdf[Historical Facts about the Leteln School (Historisches 端ber die Letelner Schule)]
