= Schaumburg Historical Background

Read: 
link:https://www.histag-schaumburg.de/page/page_ID/108?PHPSESSID=4ad5e3e9bb07873d0cecbee446a2b2b9[Historische Arbeitsgemeinschaft für Schaumburg]

== Lippe and Schaumburg-Lippe

Read:

From link:https://www.familysearch.org/en/wiki/Schaumburg-Lippe,_German_Empire_Genealogy[Schaumburg-Lippe, German Empire Genealogy]

"Schaumburg-Lippe was created as a county in 1647. Schaumburg-Lippe was a county until 1807 when it became a principality; from 1871 it
was a state within the German Empire. In 1913, it was the smallest state in the German Empire in terms of population. The capital was Bückeburg,
and Stadthagen was the only other town. It became a free state in 1918, and was until 1946 a small state in Germany. It is located in the
present day state of Lower Saxony, with its capital at Bückeburg. It should not be confused with the principality of Lippe."

=== Disambiguation: The Difference Between Schaumburg, Schaumburg-Lippe, Lippe, and Lippe-Detmold

Read:

The "Schaumburg" is a cultural/geographical area:

    Part of it, labelled "Graftschaft Schaumburg" on this map, was in Hanover (Hannover).
    Schaumburg-Lippe was the part of the Schaumburg owned by a branch of the Lippe family.

Lippe (also called Lippe-Detmold) was a principality owned by a different branch of the Lippe family

* link:https://www.familysearch.org/en/wiki/Germany_Genealogy[German Research]

== Understanding Jurisdictions


