= Genealogical Sources of the Lower Saxony State Archive

The Niedersächishes Landesarchiv has a list of genealogical sources. The 
link:file:///home/kurt/Downloads/NLA_HA_Genealogische_Quellen-1.pdf[Genealogical Sources] in the Niedersächishes Landesarchiv is in German. 
A translation is forthcoming.

== Prospective Schaumburg Genelogy Sources

This table was created by reading through the Familienforschung (Family Research) PDF links on the link:https://nla.niedersachsen.de/startseite/benutzung/nutzliche_hilfsmittel/nuetzliche-hilfsmittel-85897.html[Use Aids]
webpage of the Niedersächisches Landesarchiv. While the PDF files are from each regional departments of the Niedersächisches Landesarchiv, they were
culled for prospective sources of information for the Bleeke, Krückeberg and Weiland famailies.

These are the PDF files explaining family research sources, such as church records, civil status and civil registers that are in the Lower
Saxony regional archives:

* link:https://nla.niedersachsen.de/download/102324[NLA BU Hilfsmittel Familienforschung]
* link:https://nla.niedersachsen.de/download/198349[NLA HA Genealogische Quellen]
* link:https://nla.niedersachsen.de/download/102333[NLA HA Inventare]
* link:https://nla.niedersachsen.de/download/101352[NLA OL Leitfaden Familienforschung]
* link:https://nla.niedersachsen.de/download/94801[NLA OS Inventar zur Hof- und Familienforschung]
* link:https://nla.niedersachsen.de/download/101353[NLA OS Leitfaden Familienforschung]
* link:https://nla.niedersachsen.de/download/182942[NLA ST Genealogische Quellen]
* link:https://nla.niedersachsen.de/download/102340[NLA WO Flyer Steuer- und Schatzregister]

This is what ??/ contained:

=== Resources for genealogists in the NLA Bückeburg

There are 2 archive inventories (searchable in Arcinsys) that are of particular importance for genealogical research are of particular importance: 

1. Schaumburg emigrants, contains names and personal data of Schaumburg emigrants from the years 1820-1914. +
+
Scope: More than 14000 records; printed in: Volume 48 and Volume 54 of Schaumburger Studien (1988 and 1995 respectively). 
2. genealogical sources, index of sources of the NLA Bückeburg on the history of persons and groups of persons in Schaumburg, also suitable also suitable as an introduction to local history. Included are sources (with title and signature) that contain personal names; scope: approx. 800 titles.

* Registers of various church records compiled by genealogical users
are located in the technical user room, approx. 100 bound volumes, not complete.
not complete.

* Listing of basic literature on genealogical research also in the technical user room.

* Attached is a list of name indexes to civil status registers. In addition some of the register volumes themselves contain lists of names.

=== Summary of Prospective Sources

This table is the start of a list derived by reading through PDFlinks above:

[caption="Table :"]
.Prospective Relevant Genealogical Sources in Schaumburg and Bückeburg
[%autowidth]
|===
|Source

|Zivilstandsregister der napoleon Okkupationszeit
|===

