= Abraham Stendler

== Transliteration from old German script

Ehelicher Sohn von Jakob Stendler und Maria Elisabeth geborene Alexander
geboren in Klingen Kanton Bergzabern Königreich Bayern den 22 November
und getauft im selben Monat 1831, konfirmiert im März 1845. Er wanderte
ein in dieses Land im März 1860, arbeitete anfangs in Ohio, zog alsdann
hierher woselbst er sich alsbald der Gemeinde anschloß, und
verheirathete sich den 30 December 1862mit Jungfrau Maria Belz, eine
Tochter von Peter Belz und Elisabeth geb. Bibelheimer, geboren in
West-Penn to Schuylkill Co. Pa. den 2 Juli 1838, confirmiert den 4 Apr
1852.

Download xref:attachment$18-abraham-stendler.jpg[original image of biography].

== English Translation

Abraham Stendler,

legitimate son of Jakob Stendler and Maria Elisabeth neé Alexander, was
bon in Klingen, Kanton (district) Bergzabern, in the Kingdom of Bavaria,
on November 22^nd^ 1831. He was baptized in the same month. He was
confirmed in March 1845.

He immigrated in this country in March of 1860. He first worked in Ohio
but then later moved here, were he joined the community (parish) and
married on December 30^th^ 1862 the maiden Maria Belz, a daughter of
Peter Belz and Elisabeth neé Bibelheimer. Maria Belz had been born on
July 2^nd^ 1838 in West Pennsylvania, in Schuylkill County, Pa. She was
confirmed on April 4^th^ 1852.
