= Inventory of Church Registers

**TODO:** Add the details of

* the church registers for Petzen, Frille, Kleneenbremen, etc availbable per arcsys (for Niedersachesen)
* those available on Archion.de

Nice PDF about the xref:attachment$schaumburg-monastories-village-churches.pdf[Schauburg Klöster und Dorfkirchen].

The Kommunal Archiv Minden: https://www.kommunalarchiv-minden.de/service-angebote/personenstandsregister/

I got a reply as to the link:https://www.archion.de/de/forum/threads/wie-finde-ich-das-kirchspiel-finden-wenn-ich-nur-das-dorf-kenne.16576/[Gemeinde für Islerheide].

====
Reason: Ilserheide and associated parts may well be found in different church registers at different times.

For example, the parish register of Lahde and also the parish register of Windheim come into consideration.

Addition to Ilserheide, because there was also a spatial division!

The northern part of Ilserheide was part of the parish of Windheim, the southern part of Ilserheide was part of the parish of Lahde.

I was so disappointed that the Windheim parish register, which I would like to read, is so difficult to read.
====
