= Naming Practices

The name "Hans," is an abbreviated version of "Johannes," or "Johann,"
as in the case of today's "Don" and "Donald." Other examples of
abbreviated names are Thrine = Cathrine, Catharine or Katharine: Mina =
Wilhelmina or Wilhelmine; Gerd or Gerdt = Gerhard; Heine = Heinrich:
Cord, Cordt or Curt = Conrad; Berend, Bernt or Bern = Bernhardt or
Bernard; Fritz = Friedrich; Dorette = Dorothea or Dorothee; Line, Lina
or Lena = Caroline or Karoline; Lotte = Charlotte; Harm = Hermann; etc.

Add to the above versions the transposition of German names into
English. Many are familiar, such as Heinrich = Henry, Friedrich = Fred
or Frederick, and Wilhelm = William. Others include Karl or Carl =
Charles, Jurg or Jurgen = George, Ludwig = Louis, Elise = Elisabeth,
Arndt = Arnold, Margaretha = Margaret, Amalia = Emily, etc.

As English became the order of the day, changes in spelling also
appeared, i.e., Ernst = Ernest, Eduard = Edward, Alwine = Alvina, Louise
= Louise, Theodor = Theodore, Philipp = Phillip, Auguste = August,
Marten = Martin, Hermann = Herman, etc.

Naming practices, as explained by Larry Jensen in his article, _The
World of Germanic Names_ (published in the *German Genealogical
Digest*), might also apply to those of our ancestors who originated in
what is now northwestern Germany -- at least in part. We quote:

====
It is a tradition in most areas of Germany to pass on the given names of
the father and grandfathers to their son and grandsons. The same is true
with the given names of the mother and grandmothers. In a Buchmann
family the name Jacob was given, six generations in a row. Examples have
also been found in which the same given name has been passed down for
over four hundred years.
====

Usually the passing on the given name was very systematic and often
followed the rules below:

* first son -- father's father
* second son -- mother's father
* third son -- father's grandfather (father's side)
* fourth son -- father's grandfather (mother's side)
* fifth son -- mother's grandfather (father's side)
* sixth son -- mother's grandfather (mother's side)

The same rules applied to the daughters as well.

In a family where a child was named after the father or a grandfather,
and later that child died, you may find that the next male child born
would be given thee same name."

In some areas of Germany, it has been found that every male child's
first name was 'Johann' by the time they were confirmed or married,
however they would drop the Johann and go by their middle name."

Taken from *LANDSMANN*, Issue No. 41, March 2006 pp. 6 -- 8 Howard
Piepenbrink, Publisher.
